export { default as CartIcon } from './cartIcon/CartIcon'
export { default as HeadTitle } from './headTitle/HeadTitle'
export { default as MiniCards } from './miniCards/MiniCards'
export { default as SpinnerScreen } from './spinnerScreen/SpinnerScreen'
export { default as TitleContent } from './titleContent/TitleContent'
